### PR TITLE
changed one character, maybe fixed hyperspace releasing

### PR DESCRIPTION
**Pull request by yodabird19**
The check for hyperspace dimensions in the tryRelease function checks for capital-H "Hyperspace" in the dimension name. To my knowledge, all hyperspace dimensions on Horizon's End use a lowercase-h (the checks in SimpleProjectile.kt and StarshipMovement.kt also use lowercase-h). Assuming this is the case, this check would return false even in a dimension such as Asteri_hyperspace; now, it will return true.

### CODE REVIEW

**Comment by kwazedilla** [comment]
It would be better to instead use the condition `starship.serverLevel.world.name.lowercase().contains("hyperspace")` on the off chance that one world is named "Hyperspace"

**Comment by yodabird19** [comment]
> It would be better to instead use the condition `starship.serverLevel.world.name.lowercase().contains("hyperspace")` on the off chance that one world is named "Hyperspace"
I fully agree; the only reason I did it like this is because it's how the other hyperspace checks are done, and I wanted to standardize this one to their example (...also, a one-character commit is funny). I can make a PR with all four hyperspace checks using .lowercase() if you'd like.

**Comment by kwazedilla** [comment]
> I can make a PR with all four hyperspace checks using .lowercase() if you'd like.

Sounds like a good idea for forwards compatibility.

**Comment by Gutin1** [comment]
just do .contains("hyperspace", ignoreCase=true)

**Pull request merged**
