### PR TITLE
make all pot variants flyable

### PR DESCRIPTION
**Pull request by SciathGH**
pot was flyable but not the potted variants, thats been fixed here

### CODE REVIEW

**Comment by Peter-Crawley** [comment]
Did you test this?

**Comment by Peter-Crawley** [comment]
Did you actually?

**Comment by SciathGH** [comment]
theres a video in #development showing it working, because I knew you'd doubt me

**Comment by trainb0y1** [comment]
I think this could be better handled the way slabs and stairs are handled. Hardcoding pots bothers me lol.

**Comment by trainb0y1** [comment]
Oh, idk about its performance. I’m just saying for consistency’s sake we should stick to one or the other

**Comment by SciathGH** [comment]
fair
I can do that rn if you want

**Pull request merged**
