### PR TITLE
Update StarshipType.kt

### PR DESCRIPTION
**Pull request by CrystalzzzDeez**
i think this works like this istg if u change the power thingy to 0 sciath i will eat you alive

### CODE REVIEW

**Comment by Peter-Crawley** [comment]
i predict the build will fail

**Comment by CrystalzzzDeez** [comment]
> i predict the build will fail

if it breaks blame sciath

**Comment by SciathGH** [comment]
too late

**Comment by CrystalzzzDeez** [comment]
its your fault

**Pull request closed without merging**
