### PR TITLE
add cruiser class and ion turret

### PR DESCRIPTION
**Pull request by Crystalzzzz**
will need to be balanced on a proper test server

### CODE REVIEW

**Comment by Crystalzzzz** [comment]
conflicts of course, will rebase

**Comment by Crystalzzzz** [comment]
nevermind, rebasing made no difference

**Comment by Crystalzzzz** [comment]
will manually resolve conflicts in github editor

**Comment by Gutin1** [comment]
Jesus christ

**Comment by Crystalzzzz** [comment]
yeah ik, pls accept D:

**Comment by Crystalzzzz** [comment]
on second thought i've probably got more balancing changes and features to add, so just leave this open and i'll close it if i make changes (and hopefully untangle my car crash of conflicts)

**Comment by Crystalzzzz** [comment]
adding new features, will open a new non spaghettified pr when done

**Pull request closed without merging**
