### PR TITLE
Planet mining nerf

### PR DESCRIPTION
**Pull request by SciathGH**

### CODE REVIEW

**Comment by yodabird19** [comment]
Planet mining nerf is a horrible idea (on multiple levels) for reasons extensively discussed in the ore balancing thread on discord. Essentially everyone outside of Vega who has bothered to comment has opposed this idea. Please do not merge this request @Gutin1 🙏

**Comment by SciathGH** [comment]
Updated values with .66 the original, and 60 power per block broken

**Review by s1icedev — CHANGES_REQUESTED** [review]
change 0.000132 to 0.00132f

you made it a reduction of 2/30, not 2/3

**Comment by SciathGH** [comment]
> change 0.000132 to 0.00132f
> 
> you made it a reduction of 2/30, not 2/3

Fixed that now, and also updated the Ore config

**Pull request closed without merging**
