### PR TITLE
Detectable blocks

### PR DESCRIPTION
**Pull request by trainb0y1**
* ~~Added deepslate variants to detectable blocks~~
* Removed redundant copper stairs and slabs
* Removed a couple of * imports

### CODE REVIEW

**Comment by trainb0y1** [comment]
I just realized I added full blocks. I'll change that when I get on my computer. Don't accept this pr in the meanwhile.

**Comment by trainb0y1** [comment]
It also appears @SciathGH added full blocks for the copper variants. Are we allowing full blocks now or still sticking to double slabs?

**Comment by PiggleMcDiggle** [comment]
> It also appears @SciathGH added full blocks for the copper variants. Are we allowing full blocks now or still sticking to double slabs?

Copper only has a cut copper slab and therefore only a cut copper double slab.  Sciath likely added the copper block for this reason.  However, the cut copper block has no reason to be there, if it is.  Cut copper has a double slab alternative, as aforementioned.

**Comment by trainb0y1** [comment]
Alright, should be good now.

**Pull request merged**
